### ISSUE TITLE
No Forced Feedback

### ISSUE THREAD

**Issue by cjhelloletsgo** [JacKeTUs/universal-pidff#32]
Previously forced feedback was working for me with my Moza R5 but it has stopped working.

I think it may have been after a kernel update? When I discovered it wasn't working I uninstalled per the README then followed the instructions for installation again with the DKMS method. 

After reboot the module is loaded
![image](https://github.com/user-attachments/assets/335e2834-dc9f-4059-a6c2-c7a7a093e5c9)

I tried to confirm that forced feedback was working via the test file but it doesn't work for me.
![image](https://github.com/user-attachments/assets/bd7a9c2d-4529-406b-873d-6a7a3b73f1d6)

No forced feedback in games either.

**Comment by Lawstorant** [comment]
Please provide more info like your Distribution and it's version

**Comment by cjhelloletsgo** [comment]
This was my bad, when I ran ```sudo dmesg``` there was an error with signing. I realize now that is because I updated my motherboard firmware and that clears the keys. Re-enrolled the key and it works again. Thank You!
