### ISSUE TITLE
Moza R5 no longer recognized after restarting

### ISSUE THREAD

**Issue by ollipop-ops** [JacKeTUs/universal-pidff#33]
My Moza R5 was working fine with this driver and Boxflat but today it no longer works, I can't see any messages in dmesg and Boxflat doesn't even recognize that I have a wheel plugged in now.
I'm on LMDE6 if that helps

**Comment by Lawstorant** [comment]
Please provide output of `lsusb`, `ls /dev/serial/by-id/` and `ls /dev/input/by-id`

There haven't been any recent changes to this driver so the issue must be something i  your system.

**Comment by ollipop-ops** [comment]
I rebuilt and reinstalled the kernel module to the same issue. Weirdly enough what ended up resolving the issue was switching the USB port that my Moza R5 was plugged into and now it's working consistently. Very odd as I haven't had issues with that USB port before or since

**Comment by Lawstorant** [comment]
Computers right? Haha

**Comment by Lawstorant** [comment]
@JacKeTUs can be closed
